#!/bin/bash
set -e

##
## Set the default ini file location. Can be overwritten by the
## first argument
##
INIFILE=./coexist.ini
if [[ $1 ]];then
  INIFILE=$1
fi

##
## Helper function for parsing ini files
##
VAL=
iniVal(){
  VAL=`sed -sn -e "s/.*;.*//" -e "s/[^;]*\s*$1\s*=\s*\(.*\)/\1/p" < $INIFILE`
}

report(){
  echo "## $1"
}

DIR=`pwd`
BIN_DIR=$DIR/bin

##
## Which modules to build
##
iniVal android;BUILD_ANDROID=$VAL
iniVal server;BUILD_SERVER=$VAL

##
## Get the necessary android values from the configuration file
##
iniVal name;NAME=$VAL
iniVal image;IMAGE=$DIR/$VAL
iniVal notification;NOTIFICATION=$DIR/$VAL
iniVal package;PACKAGE=$VAL
iniVal api;API=$VAL

##
## Get the necessary web values from the configuration file
##
iniVal version;VERSION=$VAL
iniVal user;USER=$VAL
iniVal pass;PASS=$VAL
iniVal db;DB=$VAL
iniVal host;HOST=$VAL
iniVal dbms;DBMS=$VAL
iniVal create_dir;CREATE=$DIR/$VAL
iniVal schema_dir;SCHEMA=$DIR/$VAL

##
## Create the bin dir
##
mkdir -p $BIN_DIR

##
## Download the most recent version from git and configure
## it to build an android application that points to your
## server, with the icons and name you specify. The source will
## be removed after and the apk will be in this directory.
##
build_android(){
  report
  cd $BIN_DIR
  report "Downloading the latest version of Coexist Android"
  rm -rf coexist-android
#  git clone git://github.com/naddeoa/coexist-android.git > /dev/null 2>&1
  wget https://github.com/naddeoa/coexist-android/archive/master.zip > /dev/null 2>&1
  unzip master.zip
  mv coexist-android-master coexist-android
  rm master.zip
  cd coexist-android
  report "Configuring Coexist Android according to $INIFILE"
  ./configure  \
    -i "$IMAGE"  \
    -I "$NOTIFICATION"  \
    -n $NAME \
    -p $PACKAGE \
    -h $API
  make 2>&1
  report "Copying apks to $BIN_DIR/bin"
  cp bin/*.apk $BIN_DIR
}
if [[ $BUILD_ANDROID = "on" ]];then
  build_android
fi

##
## Configure the web stuff if its enabled in the ini file
##
build_server(){
  report
  cd $BIN_DIR
  report "Downloading the latest version of Coexist Server"
  rm -rf coexist-server
#  git clone git://github.com/naddeoa/coexist-server.git > /dev/null 2>&1
  wget https://github.com/naddeoa/coexist-server/archive/master.zip > /dev/null 2>&1
  unzip master.zip
  mv coexist-server-master coexist-server
  rm master.zip
  cd coexist-server
  report "Configuring Coexist Android according to $INIFILE"
  ./configure \
    -v $VERSION \
    -u $USER \
    -p $PASS \
    -d $DB \
    -c $CREATE \
    -s $SCHEMA \
    -m $DBMS \
    -h $HOST
  report "Tarring the website to $BIN_DIR/bin"
  tar -zcf $BIN_DIR/$NAME-web.tgz *
}
if [[ $BUILD_SERVER = "on" ]];then
  build_server
fi

##
## Scp the files to the server if a scp_to field was
## defined in the .ini file.
##
cd $DIR
iniVal scp_to;SCP=$VAL
iniVal scp_port
if [[ $VAL ]];then
  SCP_PORT="-P $VAL"
fi
if [[ $SCP ]];then
  report "Copying the files to your server so you can untar them."
  scp $SCP_PORT bin/*.apk bin/*tgz $SCP 
fi

